name: pikvn_client
description: A client to upload your photos (local file, remote url..etc) to https://2.pik.vn. Supports resize images on the fly
version: 0.0.7
homepage: https://github.com/andy1xx8/pikvn-client-dart
repository: https://github.com/andy1xx8/pikvn-client-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  image: ^3.0.2

dev_dependencies:
  test: ^1.14.4
